sudo: required
services:
  - docker

script:
  - docker build -t heeleeaz/tomcat-server:latest -t heeleeaz/tomcat-server:$SHA Dockerfile.dev .

  - docker push heeleeaz/tomcat-server:latest
  - docker push heeleeaz/tomcat-server:$SHA

  - kubectl apply -f k8s
