sudo: required
services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)

script:
  - docker build -t heeleeaz/tomcat-server:latest -t heeleeaz/tomcat-server:$SHA -f Dockerfile.dev .

  - docker push heeleeaz/tomcat-server:latest
  - docker push heeleeaz/tomcat-server:$SHA

  - kubectl apply -f k8s
